const fs = require('fs');
const lines = fs.readFileSync('src/app/meet/[id]/page.js', 'utf8').split('\n');

const newLines = [];
newLines.push("'use client';");
newLines.push("");
newLines.push("import { useState, useRef, useEffect } from 'react';");
newLines.push("import { useParams, useRouter, useSearchParams } from 'next/navigation';");
newLines.push("import VideoGrid from '../components/VideoGrid';");
newLines.push("");
newLines.push("import { C, Avatar, IconBtn, PillBtn } from '../components/ui';");
newLines.push("import SettingsPanel from '../components/SettingsPanel';");
newLines.push("import ChatPanel from '../components/ChatPanel';");
newLines.push("import PollsPanel from '../components/PollsPanel';");
newLines.push("import ParticipantsPanel from '../components/ParticipantsPanel';");
newLines.push("import ControlsBar from '../components/ControlsBar';");
newLines.push("import PollModal from '../components/PollModal';");
newLines.push("import GlobalStyles from '../components/GlobalStyles';");
newLines.push("import { useMeetConnection } from '../hooks/useMeetConnection';");
newLines.push("");
newLines.push("export default function MeetPage() {");
newLines.push("  const { id } = useParams();");
newLines.push("  const router = useRouter();");
newLines.push("  const searchParams = useSearchParams();");
newLines.push("  const encryptionKeyRef = useRef(null);");
newLines.push("  const [activePanel, setActivePanel] = useState(null);");
newLines.push("");
newLines.push("  useEffect(() => {");
newLines.push("    if (typeof window !== 'undefined') {");
newLines.push("      let hash = window.location.hash.replace('#', '');");
newLines.push("      if (!hash) {");
newLines.push("        hash = Array.from(crypto.getRandomValues(new Uint8Array(8))).map(b => b.toString(16).padStart(2, '0')).join('');");
newLines.push("        window.history.replaceState(null, null, `#${hash}`);");
newLines.push("      }");
newLines.push("      encryptionKeyRef.current = id + '-' + hash;");
newLines.push("    }");
newLines.push("  }, [id]);");
newLines.push("");
newLines.push("  const conn = useMeetConnection({ id, router, searchParams, encryptionKeyRef, activePanel, setActivePanel });");
newLines.push("  const { authorized, accessDenied, myStream, remoteStreams, micActive, videoActive, isScreenSharing, statusMsg, userProfile, meetLimits, isHandRaised, isHostUser, roomSettings, meetingTimer, floatingReactions, showReactionPicker, setShowReactionPicker, chatMessages, newMessage, setNewMessage, chatEndRef, unreadCount, polls, showPollModal, setShowPollModal, pollForm, setPollForm, toggleMic, toggleVideo, toggleScreenShare, toggleHandRaise, handleSendMessage, handleSendReaction, toggleBlockPeer, toggleGlobal, endCall, remotePeerIds } = conn;");
newLines.push("");

// Original Lines 617-695
for(let i=617; i<=695; i++) {
  newLines.push(lines[i]);
}

newLines.push("");
newLines.push("      {/* ── Body ── */}");
newLines.push("      <div style={{ flex: 1, display: 'flex', minHeight: 0, overflow: 'hidden' }}>");
newLines.push("        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', position: 'relative', minWidth: 0 }}>");
newLines.push("");
newLines.push("          <VideoGrid");
newLines.push("            remotePeerIds={remotePeerIds}");
newLines.push("            remoteStreams={remoteStreams}");
newLines.push("            localStream={myStream}");
newLines.push("            videoActive={videoActive}");
newLines.push("            micActive={micActive}");
newLines.push("            userProfile={userProfile}");
newLines.push("            isLocalScreenSharing={isScreenSharing}");
newLines.push("          />");
newLines.push("");
newLines.push("          {/* Floating Reactions */}");
newLines.push("          <div style={{ position: 'absolute', bottom: '7rem', left: '1.5rem', pointerEvents: 'none', zIndex: 20, display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>");
newLines.push("            {floatingReactions.map(r => (");
newLines.push("              <div key={r.id} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(10px)', padding: '0.35rem 0.75rem', borderRadius: 20, border: `1px solid ${C.border}`, animation: 'floatUp 3.5s ease-out forwards', fontSize: '0.82rem' }}>");
newLines.push("                <span style={{ fontSize: '1.1rem' }}>{r.emoji}</span>");
newLines.push("                <span style={{ color: '#d4d4d8', fontWeight: 600 }}>{r.sender}</span>");
newLines.push("              </div>");
newLines.push("            ))}");
newLines.push("          </div>");
newLines.push("");
newLines.push("          <ControlsBar {...conn} />");
newLines.push("        </div>");
newLines.push("");
newLines.push("        {/* ── Side Panels ── */}");
newLines.push("        {activePanel === 'chat' && <ChatPanel onClose={() => setActivePanel(null)} chatMessages={chatMessages} userProfile={userProfile} chatEndRef={chatEndRef} newMessage={newMessage} setNewMessage={setNewMessage} handleSendMessage={handleSendMessage} />}");
newLines.push("        {activePanel === 'participants' && <ParticipantsPanel onClose={() => setActivePanel(null)} remotePeerIds={remotePeerIds} remoteStreams={remoteStreams} isHostUser={isHostUser} roomSettings={roomSettings} userProfile={userProfile} isHandRaised={isHandRaised} micActive={micActive} videoActive={videoActive} toggleGlobal={toggleGlobal} toggleBlockPeer={toggleBlockPeer} />}");
newLines.push("        {activePanel === 'polls' && <PollsPanel onClose={() => setActivePanel(null)} isHostUser={isHostUser} setShowPollModal={setShowPollModal} polls={polls} userProfile={userProfile} id={id} />}");
newLines.push("        {activePanel === 'settings' && <SettingsPanel onClose={() => setActivePanel(null)} id={id} isHostUser={isHostUser} roomSettings={roomSettings} toggleGlobal={toggleGlobal} meetLimits={meetLimits} />}");
newLines.push("      </div>");
newLines.push("");
newLines.push("      <PollModal showPollModal={showPollModal} setShowPollModal={setShowPollModal} pollForm={pollForm} setPollForm={setPollForm} id={id} encryptionKeyRef={encryptionKeyRef} />");
newLines.push("");
newLines.push("      <GlobalStyles />");
newLines.push("    </div>");
newLines.push("  );");
newLines.push("}");

fs.writeFileSync('src/app/meet/[id]/page.js', newLines.join('\n'));
